export type DocumentSourceKind = "auto" | "manual" | "fixed";
export type DocumentHandlingKind = "internal-form" | "auto-generated" | "upload-or-link" | "fixed-guidance";

export type TripDocumentDefinition = {
  key: string;
  category: string;
  title: string;
  description: string;
  sourceKind: DocumentSourceKind;
  handlingKind: DocumentHandlingKind;
  editUrl?: (tripId: string) => string;
};

export const documentCatalog: TripDocumentDefinition[] = [
  {
    key: "trip-role-definitions",
    category: "פרטי הטיול והיערכות",
    title: "הגדרות תפקיד אחראי טיול",
    description: "ריכוז אחריות אחראי הטיול לפי משימות הלו״ז: בהיערכות, בשעת מעשה ואחר מעשה, עם שיוך לשלב בטיול.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/trip-role-definitions`,
  },
  {
    key: "staff-role-definitions",
    category: "פרטי הטיול והיערכות",
    title: "הגדרות תפקיד צוות הטיול",
    description: "ריכוז אחריות לכל אחראי שהוגדר במשימות הלו״ז, לפי שלבי ההיערכות, ביצוע וסיום.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/staff-role-definitions`,
  },
  {
    key: "schedule-safety-highlights",
    category: "פרטי הטיול והיערכות",
    title: "לו״ז ודגשי בטיחות",
    description: "מסלול הטיול המפורט, כל שלבי היום, דגשי הבטיחות והחלופות הנדרשות לפי תנאי המסלול ומזג האוויר.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/schedule-safety`,
  },
  {
    key: "risk-management",
    category: "פרטי הטיול והיערכות",
    title: "ניהול סיכונים",
    description: "טבלת ניהול סיכונים לפי נספח ט״ז: גורמי סיכון, תרחישים אפשריים, פעולות מניעה ואחראים לביצוע.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/risk-management`,
  },
  {
    key: "safety-department-review-tracking",
    category: "פרטי הטיול והיערכות",
    title: "טבלת מעקב לביקורת מחלקת הבטיחות",
    description: "טבלת שליטה לבדיקת השלמת מסמכי תיק הטיול, הערות הביקורת ואישור מחלקת הבטיחות.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/safety-review-tracking`,
  },
  {
    key: "moked-teva-approval",
    category: "אישורי הטיול",
    title: "אישור מוקד טבע / לשכה לתיאום טיולים",
    description: "אישור שמונפק במערכת מוקד טבע/הלשכה לתיאום טיולים ומועלה לכאן כקובץ PDF או תמונה.",
    sourceKind: "manual",
    handlingKind: "upload-or-link",
  },
  {
    key: "appendix-c-trip-leader-appointment",
    category: "אישורי הטיול",
    title: "כתב מינוי לאחראי הטיול",
    description: "נספח ג׳ - כתב מינוי רשמי לאחראי הטיול מטעם מזכ\"לית הארגון.",
    sourceKind: "manual",
    handlingKind: "internal-form",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/appendix-c`,
  },
  {
    key: "secretary-and-trip-coordinator-approval",
    category: "אישורי הטיול",
    title: "אישור מזכ\"לית ורכז טיולים",
    description: "מסמך חתימה המאשר שהמזכ״לית ורכז הטיולים עברו על תוכנית הטיול, ההיערכות וההנחיות והטיול מאושר לביצוע.",
    sourceKind: "manual",
    handlingKind: "internal-form",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/secretary-trip-coordinator-approval`,
  },
  {
    key: "police-approvals",
    category: "אישורי הטיול",
    title: "אישורי משטרה / היעדר עבירות מין",
    description: "אישורי משטרה והיעדר מניעה להעסקה למדריכים, נהגים, חובשים, מאבטחים ונותני שירות רלוונטיים.",
    sourceKind: "manual",
    handlingKind: "upload-or-link",
  },
  {
    key: "business-license-insurance",
    category: "אישורי הטיול",
    title: "רישיונות וביטוחים של המקום",
    description: "רישיון עסק, ביטוח בתוקף ואישורי משרד הבריאות/בטיחות לכל אתר, מפעיל, אטרקציה, לינה או קייטרינג.",
    sourceKind: "manual",
    handlingKind: "upload-or-link",
  },
  {
    key: "medic-security-certificates",
    category: "אישורי הטיול",
    title: "תעודות ואישור חובש ומאבטח",
    description: "תעודות הכשרה ואישורים בתוקף למלווים רפואיים, חובשים, מאבטחים ונושאי נשק לפי דרישות חוזר מנכ״ל ואישור הטיול.",
    sourceKind: "manual",
    handlingKind: "upload-or-link",
  },
  {
    key: "participant-list",
    category: "חניכים וצוות",
    title: "רשימת חניכים + אישורי הורים",
    description: "רשימת כל החניכים המשתתפים בטיול, פרטי התקשרות, אישורי הורים, הצהרת בריאות ואישורים מיוחדים כמו רחצה או פעילות מים.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/participant-list`,
  },
  {
    key: "trip-entry-registration",
    category: "חניכים וצוות",
    title: "רישום לכניסה חניכים + צוות",
    description: "רשימת כניסה ונוכחות ביום הטיול לצורך בקרה, ספירה והשוואה לרשימות המאושרות.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/trip-entry-registration`,
  },
  {
    key: "medical-sensitivities",
    category: "חניכים וצוות",
    title: "רשימת חניכים עם בעיה רפואית/רגישות/אלרגיה",
    description: "ריכוז מגבלות רפואיות, אלרגיות, ציוד אישי נדרש, הנחיות הורים ודגשים למסירה לחובש, למדריכים ולאחראי הסעה.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
  },
  {
    key: "staff-list",
    category: "חניכים וצוות",
    title: "רשימה של הצוות",
    description: "רשימת צוות ההדרכה והליווי של הטיול, תפקידים, טלפונים, פרטי קשר ואישורים נדרשים.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/staff-list`,
  },
  {
    key: "essential-contact-list",
    category: "חניכים וצוות",
    title: "רשימת קשר חיונית לטיול",
    description: "רשימת טלפונים חיוניים ורלוונטיים לטיול: מוקדי חירום, גורמי ארגון ובטיחות, וכל תקני הצוות המאושרים.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/essential-contact-list`,
  },
  {
    key: "participant-groups",
    category: "חניכים וצוות",
    title: "רשימת חניכים לפי קבוצות",
    description: "רשימות קבוצתיות למדריכים, כולל מספר חניכים, שם מדריך, פרטי קשר ודגשים רלוונטיים לכל קבוצה.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/participant-groups`,
  },
  {
    key: "bus-participant-assignments",
    category: "הסעות",
    title: "רשימת חניכים לפי הסעות",
    description: "רשימות חניכים וצוות לפי אוטובוסים, כולל אחראי הסעה, מספר חניכים, מספר צוות, מרכז והערות.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/bus-participant-assignments`,
  },
  {
    key: "transport-table",
    category: "הסעות",
    title: "טבלת שליטה בהסעות",
    description: "טבלת שליטה בהסעות: אחראי הסעה, טלפון, כתובת ושעת יציאה, נהג, חברת הסעות ואישורים שנשלחו.",
    sourceKind: "auto",
    handlingKind: "auto-generated",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/transport-table`,
  },
  {
    key: "bus-pre-departure-check",
    category: "הסעות",
    title: "בדיקת אוטובוס לפני יציאה",
    description: "נספח ט״ו - בדיקת האוטובוס לפני יציאה: אישור קצין בטיחות, רישיון נהג, גיל אוטובוס, חגורות, מים, אלונקה ותיק עזרה ראשונה.",
    sourceKind: "manual",
    handlingKind: "fixed-guidance",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/bus-pre-departure-check`,
  },
  {
    key: "bus-responsible-teacher-guidelines",
    category: "הסעות",
    title: "הנחיות למורה האחראי על האוטובוס",
    description: "נספח י״ג - הנחיות למורה האחראי על האוטובוס: ספירות, ירידה ועלייה, התנהגות בנסיעה, קשר עם הנהג ובקרת נוכחות.",
    sourceKind: "fixed",
    handlingKind: "fixed-guidance",
  },
  {
    key: "student-briefing",
    category: "תדרוכים והודעות",
    title: "תדרוך לחניכים",
    description: "תדרוך חובה לחניכים לפני היציאה: כללי בטיחות, התנהגות, נסיעה, הליכה, משמעת, מצב חירום ודגשים לפי אופי הטיול.",
    sourceKind: "fixed",
    handlingKind: "fixed-guidance",
  },
  {
    key: "student-letter-equipment",
    category: "תדרוכים והודעות",
    title: "מכתב לחניכים",
    description: "מכתב לחניכים ולהורים עם הנחיות, רשימת ציוד, שעות, נקודות איסוף, כללי התנהגות ודגשים מיוחדים לטיול.",
    sourceKind: "manual",
    handlingKind: "internal-form",
  },
  {
    key: "reporting-chain",
    category: "תדרוכים והודעות",
    title: "שרשרת דיווח",
    description: "סדר הדיווח במקרה חירום או שינוי במהלך הטיול: אחראי טיול, מנהל/מזכ״לית, רכז טיולים, חדר מצב, קב״ט וגורמי סיוע.",
    sourceKind: "fixed",
    handlingKind: "fixed-guidance",
  },
  {
    key: "emergency-incident-report",
    category: "חירום ורפואה",
    title: "דוח אירוע חירום",
    description: "טופס לתיעוד אירוע חירום במהלך הטיול: פרטי האירוע, מיקום, מעורבים, פעולות שבוצעו, דיווחים והחלטות המשך.",
    sourceKind: "manual",
    handlingKind: "internal-form",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/emergency-incident-report`,
  },
  {
    key: "medical-referral",
    category: "חירום ורפואה",
    title: "הפניה למיון / טיפול רפואי",
    description: "נספח א״י - טופס הפניה לטיפול רפואי לתלמיד שנפגע בטיול, כולל פרטי תלמיד, נסיבות הפגיעה, טיפול ראשוני ומלווה אחראי.",
    sourceKind: "manual",
    handlingKind: "internal-form",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/medical-referral`,
  },
  {
    key: "casualties-summary",
    category: "חירום ורפואה",
    title: "טבלת ריכוז נפגעים",
    description: "טבלה לריכוז פרטי נפגעים במקרה של כמה נפגעים: סטטוס, מיקום, טיפול, פינוי, בית חולים, קשר עם הורים ודיווחים.",
    sourceKind: "manual",
    handlingKind: "internal-form",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/casualties-summary`,
  },
  {
    key: "emergency-procedure",
    category: "חירום ורפואה",
    title: "התנהלות במצבי חירום",
    description: "נוהל קבוע להתנהלות במצבי חירום: פציעה, פינוי, אירוע ביטחוני, מזג אוויר קיצוני, שינוי מסלול ודיווח לחדר מצב.",
    sourceKind: "fixed",
    handlingKind: "fixed-guidance",
    editUrl: (tripId) => `/dashboard/trip/${tripId}/plan/documents/emergency-procedure`,
  },
];
